# regulatory_actions.yaml
# Defines the different types of regulatory actions (registration, licensing, tonnage, etc.)
# Includes state-specific terms, document markers, and regex patterns for identification.

version: "1.0.0"
last_updated: "2024-03-14"
description: "Defines regulatory actions, document types, status types, and workflow status"

regulatory_actions:
  # Document classification structure
  base_types:
    NEW:
      description: "New product registration application"
      patterns:
        - regex: "(?i)\\b(new|initial)\\s+(?:product\\s+)?registration\\b"
          confidence: 0.9
        - regex: "(?i)\\bfirst\\s+time\\s+registration\\b"
          confidence: 0.8
      required_fields: ["company_name", "product_name", "state"]
      
    RENEW:
      description: "Renewal application for existing registration"
      patterns:
        - regex: "(?i)\\b(?:registration\\s+)?renewal\\b"
          confidence: 0.9
        - regex: "(?i)\\brenew(?:al)?\\s+(?:of\\s+)?registration\\b"
          confidence: 0.9
      required_fields: ["company_name", "product_name", "state", "previous_registration_number"]
      
    TONNAGE:
      description: "Tonnage reporting for distributed products"
      patterns:
        - regex: "(?i)\\btonnage\\s+report\\b"
          confidence: 0.95
        - regex: "(?i)\\b(?:quarterly|annual)\\s+tonnage\\b"
          confidence: 0.9
      required_fields: ["company_name", "reporting_period", "state"]
      
    CERT:
      description: "Registration certificate or approval"
      patterns:
        - regex: "(?i)\\b(?:registration\\s+)?certificate\\b"
          confidence: 0.95
        - regex: "(?i)\\bcertificate\\s+of\\s+registration\\b"
          confidence: 0.95
      required_fields: ["company_name", "product_name", "registration_number", "state"]
      
    LABEL:
      description: "Product label or label amendment"
      patterns:
        - regex: "(?i)\\bproduct\\s+label\\b"
          confidence: 0.95
        - regex: "(?i)\\blabel\\s+amendment\\b"
          confidence: 0.9
      required_fields: ["company_name", "product_name", "state"]

  # GTD-style status classification
  status_types:
    ACTION_REQUIRED:
      description: "Requires immediate action or response"
      patterns:
        - regex: "(?i)\\b(due|submit|required|payment|deadline)\\b"
          confidence: 0.9
        - regex: "(?i)\\bby\\s+\\w+\\s+\\d{1,2}(?:st|nd|rd|th)?\\b"
          confidence: 0.9
        - regex: "(?i)\\baction\\s+required\\b"
          confidence: 0.95
      flags: ["URGENT", "DUE_DATE"]
      
    INFO:
      description: "Informational only, no action needed"
      patterns:
        - regex: "(?i)\\b(confirm|receipt|approved|completed|processed)\\b"
          confidence: 0.9
        - regex: "(?i)\\bfor\\s+your\\s+(?:records|information)\\b"
          confidence: 0.9
        - regex: "(?i)\\bhas\\s+been\\s+(?:received|processed|approved)\\b"
          confidence: 0.9
      flags: ["NOTIFICATION"]
      
    REFERENCE:
      description: "Important reference material to retain"
      patterns:
        - regex: "(?i)\\b(keep|retain|reference|official)\\b"
          confidence: 0.9
        - regex: "(?i)\\bfor\\s+your\\s+records\\b"
          confidence: 0.95
        - regex: "(?i)\\bregistration\\s+certificate\\b"
          confidence: 0.95
      flags: ["PERMANENT_RECORD"]

  # Workflow status tracking
  workflow_status:
    SUBMITTED:
      description: "Document has been submitted"
      next_states: ["PENDING", "APPROVED", "REJECTED"]
      
    PENDING:
      description: "Under review or awaiting processing"
      next_states: ["APPROVED", "REJECTED"]
      
    APPROVED:
      description: "Document has been approved"
      next_states: []
      
    REJECTED:
      description: "Document has been rejected"
      next_states: []

  # Detailed regulatory action definitions with document markers
  registration:
    canonical_name: "Product Registration"
    document_markers:
      required_fields:
        - "company name"
        - "product name"
        - "guaranteed analysis" #Common to fertilizer
        - "ingredients" # Or "active ingredients"
      typical_headers:
        - "(?i)Product Registration Form"
        - "(?i)New Registration Application"
        - "(?i)Application for Registration"
        - "(?i)Registration Form"
      typical_sections:
        - "(?i)Product Information"
        - "(?i)Company Information"
        - "(?i)Fee Calculation"  #Might be present
        - "(?i)Guaranteed Analysis"
        - "(?i)Ingredients"
        - "(?i)Directions for Use"
      # State-specific overrides *within* document_markers can go here.
      state_specific: {} #Placeholder
    state_terms:
      - term: "New Registration"
        states: []
        patterns:
          - regex: "(?i)\\bnew\\s+registration\\b"
            confidence: 0.9
      - term: "Initial Registration"
        states: []
        patterns:
          - regex: "(?i)\\binitial\\s+registration\\b"
            confidence: 0.9
      - term: "Product Registration"
        states: []
        patterns:
          - regex: "(?i)\\bproduct\\s+registration\\b"
            confidence: 0.95
      - term: "Label Submission" #Sometimes this is all that is required
        states:  ["AL", "AZ", "FL", "GA", "IA", "KS", "LA", "ME", "MO", "NC", "NE", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WV", "WY"]
        patterns:
            - regex: "(?i)\\blabel\\s+submission\\b"
              confidence: 0.95
            - regex: "(?i)\\bsubmit(?:ting)?\\s+label\\b" # Handles "submit label" and "submitting label"
              confidence: 0.9
            - regex: "(?i)\\blabel\\s+only\\b"
              confidence: 0.8
      - term: "Guidance" #For CA seed treatment
        states: ["CA"]
        patterns:
            - regex: "(?i)\\bguidance\\b"
              confidence: 0.9
      - term: "Registration" #Catch all for when not specified as New or Initial
        states: ["AR", "AZ", "CA", "CO", "CT", "DE", "GA", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WV", "WY"]
        patterns: #add a general regex for Registration
          - regex: "(?i)\\bregistration\\b"
            confidence: 0.85  # Slightly lower confidence, as it's very general
      - term: "Regulated with License" #Added because some states have this designation
        states: ["FL", "KY"]
        patterns:
          - regex: "(?i)\\bregulated\\s+with\\s+license\\b" # Example
            confidence: 0.9

  licensing:
    canonical_name: "Company Licensing"
    document_markers:
        required_fields:
            - "company name"
            - "company address"
        typical_headers:
            - "(?i)license application"
            - "(?i)permit application"
            - "(?i)application for license"
        typical_sections:
            - "(?i)company information"
            - "(?i)facility information"
            - "(?i)contact information"
            - "(?i)fee schedule"

    state_terms:
      - term: "License"
        states: ["AR", "CO", "CT", "FL", "GA", "IA", "IL", "KY", "LA", "ME", "MN", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WV", "WY"]
        patterns:
              - regex: "(?i)\\blicense\\b"
                confidence: 0.9
      - term: "Permit"  # Sometimes used interchangeably with License
        states: ["AL","CT","FL", "GA", "MO"]
        patterns:
              - regex: "(?i)\\bpermit\\b"
                confidence: 0.9
      - term: "Fertilizer Dealer Permit"
        states: ["AL"]
        patterns:
              - regex: "(?i)\\bfertilizer\\s+dealer\\s+permit\\b"
                confidence: 0.95
      - term: "Fertilizer Manufacturers Permit"
        states: ["AL"]
        patterns:
            - regex: "(?i)\\bfertilizer\\s+manufacturers?\\s+permit\\b" #Handles manufacturer/manufacturers
              confidence: 0.95
      - term: "Fertilizing Material License"
        states: ["CA"]
        patterns:
            - regex: "(?i)\\bfertilizing\\s+material\\s+license\\b"
              confidence: 0.95
      - term: "Commercial Fertilizer License"
        states: ["AZ", "GA", "MA"]
        patterns:
            - regex: "(?i)\\bcommercial\\s+fertilizer\\s+license\\b"
              confidence: 0.95
      - term: "Lime Location Permit"
        states: ["AL"]
        patterns:
            - regex: "(?i)\\blime\\s+location\\s+permit\\b"
              confidence: 0.95
      - term: "Facility License"
        states: ["AR"]
        patterns:
            - regex: "(?i)\\bfacility\\s+license\\b"
              confidence: 0.9
      - term: "Fertilizer Distributor Permit"
        states: ["IL"]
        patterns:
              - regex: "(?i)\\bfertilizer\\s+distributor\\s+permit\\b"
                confidence: 0.95
      - term: "Fertilizer Mixing Facility" # Specific to DE
        states: ["DE"]
        patterns:
            - regex: "(?i)\\bfertilizer\\s+mixing\\s+facility\\b"
              confidence: 0.95
      - term: "Lime Company License"
        states: ["GA", "IA", "MO"]
        patterns:
            - regex: "(?i)\\blime\\s+company\\s+license\\b"
              confidence: 0.95
      - term: "Fertilizer Manufacturer/Dealers License"
        states: ["IA"]
        patterns:
            - regex: "(?i)\\bfertilizer\\s+manufacturer\\s*/\\s*dealers?\\s+license\\b" #Handles /, and plural
              confidence: 0.95
      - term: "Distributor's License"
        states: ["ND"]
        patterns:
              - regex: "(?i)\\bdistributor'?s\\s+license\\b" #Handles possessive
                confidence: 0.95
      - term: "Bulk Specialty Fertilizer License"  # Specific to KY
        states: ["KY"]
        patterns:
            - regex: "(?i)\\bbulk\\s+specialty\\s+fertilizer\\s+license\\b"
              confidence: 0.95
      - term: "Custom Mix Farm Fertilizers Only"  # Specific to KY
        states: ["KY"]
        patterns:
            - regex: "(?i)\\bcustom\\s+mix\\s+farm\\s+fertilizers?\\s+only\\b"
              confidence: 0.95
      - term: "Custom Mix Specialty Fertilizer" # Specific to KY
        states: ["KY"]
        patterns:
            - regex: "(?i)\\bcustom\\s+mix\\s+specialty\\s+fertilizer\\b"
              confidence: 0.95
      - term: "Fertilizer Blender License"
        states: ["KS"]
        patterns:
            - regex: "(?i)\\bfertilizer\\s+blender\\s+license\\b"
              confidence: 0.95
      - term: "Lime Production Site License"
        states: ["KS"]
        patterns:
            - regex: "(?i)\\blime\\s+production\\s+site\\s+license\\b"
              confidence: 0.95
      - term: "Permit to Move Regulated Organisms" #added based on FL
        states: ["FL"]
        patterns:
            - regex: "(?i)\\permit\\s+to\\s+move\\s+regulated\\s+organisms?\\b"
              confidence: 0.9

  renewal:
    canonical_name: "Registration Renewal"
    state_terms:
      - term: "License Renewal"
        states: []
        patterns:
            - regex: "(?i)\\blicense\\s+renewal\\b"
              confidence: 0.9
      - term: "Annual Renewal"
        states: []
        patterns:
            - regex: "(?i)\\bannual\\s+renewal\\b"
              confidence: 0.9
      - term: "Registration Maintenance"
        states: []
        patterns:
          - regex: "(?i)\\bregistration\\s+maintenance\\b"
            confidence: 0.8 #Slightly lower, as "maintenance" is more general

  tonnage:
    canonical_name: "Tonnage Reporting"
    document_markers:
        required_fields:
          - "reporting period" #e.g "Jan-June 2024"
          - "tons sold" # or similar phrasing.
          - "company name"
          - "license number" # often required
        typical_headers:
            - "(?i)tonnage report"
            - "(?i)fertilizer tonnage"
            - "(?i)sales report"
            - "(?i)distribution report"
        typical_sections:
          - "(?i)sales by county" #Common breakdown
          - "(?i)total tons"
          - "(?i)payment information"
    state_terms:
      - term: "Tonnage Report"
        states:  ["CT", "DE", "FL", "GA", "IA", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "MI", "MN", "MS", "MO", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WV", "WY"]
        patterns:
           - regex: "(?i)\\btonnage\\s+report\\b"
             confidence: 0.95
           - regex: "(?i)\\btons?\\s+sold\\b" # "ton sold" or "tons sold"
             confidence: 0.8
      - term: "Inspection Fee" #Many states collect fees based on tonnage
        states: ["AL", "AR","AZ", "CA", "CO", "CT", "DE", "FL", "GA", "IA", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MS", "MO", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WV", "WY"]
        patterns:
            - regex: "(?i)\\binspection\\s+fee\\b"
              confidence: 0.9
      - term: "Mill Fee"
        states: ["AL", "AR", "AZ", "CA", "CO", "CT", "DE", "FL", "GA", "IA", "KS", "KY", "LA", "ME", "MN", "MS", "MT", "NC", "ND", "NE", "NJ", "NM", "NV", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WV", "WY"]
        patterns:
           - regex: "(?i)\\bmill\\s+fee\\b"
             confidence: 0.9
      - term: "Sales Report" #Less specific, lower confidence
        states: []
        patterns:
            - regex: "(?i)\\bsales\\s+report\\b"
              confidence: 0.7
      - term: "Quarterly Report"
        states: []
        patterns:
            - regex: "(?i)\\bquarterly\\s+report\\b"
              confidence: 0.8
      - term: "Semi-Annual Report"
        states: []
        patterns:
            - regex: "(?i)\\bsemi-?annual\\s+report\\b"
              confidence: 0.8
      - term: "Monthly Report"
        states:  ["FL"]
        patterns:
            - regex: "(?i)\\bmonthly\\s+report\\b"
              confidence: 0.8
      - term: "Annual Report"
        states: []
        patterns:
            - regex: "(?i)\\bannual\\s+report\\b"
              confidence: 0.8
      - term: "Fertilizer Large Package Fees"  #Specific to CO
        states: ["CO"]
        patterns:
            - regex: "(?i)\\bfertilizer\\s+large\\s+package\\s+fees?\\b"
              confidence: 0.9
      - term: "Fertilizer Small Package Fees" #Specific to CO
        states: ["CO"]
        patterns:
            - regex: "(?i)\\bfertilizer\\s+small\\s+package\\s+fees?\\b"
              confidence: 0.9
      - term: "Large & Small Package Inspection Fees" #Specific to CO
        states: ["CO"]
        patterns:
            - regex: "(?i)\\blarge\\s+&\\s+small\\s+package\\s+inspection\\s+fees?\\b" #Handles ampersand
              confidence: 0.95
      - term: "Specialty Distribution fees" #CO, archived
        states: ["CO"]
        patterns:
          - regex: "(?i)\\bspecialty\\s+distribution\\s+fees?\\b"
            confidence: 0.9
      - term: "Quarterly Materials Mill Fees" #CA
        states: ["CA"]
        patterns:
          - regex: "(?i)\\bquarterly\\s+materials?\\s+mill\\s+fees?\\b"
            confidence: 0.95
      - term: "Semi-Ann Com Fert Reports" #CA
        states: ["CA"]
        patterns:
            - regex: "(?i)\\bsemi-?annual\\s+com(?:mercial)?\\s+fert(?:ilizer)?\\s+reports?\\b" #Handles "com" and "fert"
              confidence: 0.9
      - term: "Lime Quarterly Tonnage Report" #AR
        states: ["AR"]
        patterns:
            - regex: "(?i)\\blime\\s+quarterly\\s+tonnage\\s+report\\b"
              confidence: 0.95
      - term: "Lime Reporting" #AL
        states: ["AL"]
        patterns:
            - regex: "(?i)\\blime\\s+reporting\\b"
              confidence: 0.9
      - term: "Lime Semi-Annual Tonnage" #DE
        states: ["DE"]
        patterns:
            - regex: "(?i)\\blime\\s+semi-?annual\\s+tonnage\\b"
              confidence: 0.95
      - term: "Lime Annual Tonnage" #GA
        states: ["GA"]
        patterns:
            - regex: "(?i)\\blime\\s+annual\\s+tonnage\\b"
              confidence: 0.95
      - term: "Soil Plant Amend Large Package Fees" #CO
        states: ["CO"]
        patterns:
            - regex: "(?i)\\bsoil\\s+plant\\s+amend(?:ment)?\\s+large\\s+package\\s+fees?\\b"
              confidence: 0.95
      - term: "Soil Plant Amend Small Package Fees" #CO
        states: ["CO"]
        patterns:
            - regex: "(?i)\\bsoil\\s+plant\\s+amend(?:ment)?\\s+small\\s+package\\s+fees?\\b"
              confidence: 0.95
      - term: "SA Inspection fee and sales reports" #AR
        states: ["AR"]
        patterns:
            - regex: "(?i)\\bsa\\s+inspection\\s+fee\\s+and\\s+sales\\s+reports?\\b" #Handles plural
              confidence: 0.95
      - term: "Annual Inspection Fees and Reports" #AZ
        states: ["AZ"]
        patterns:
            - regex: "(?i)\\bannual\\s+inspection\\s+fees?\\s+and\\s+reports?\\b"
              confidence: 0.95
      - term: "Quarterly Inspection Fees and Reports" #AZ
        states: ["AZ"]
        patterns:
            - regex: "(?i)\\bquarterly\\s+inspection\\s+fees?\\s+and\\s+reports?\\b"
              confidence: 0.95

      - term: "Tonnage Report (Amend)" #CT
        states: ["CT"]
        patterns:
            - regex: "(?i)\\btonnage\\s+report\\s+\\(amend\\)"
              confidence: 0.9
      - term: "Tonnage Report (Fert)" #CT
        states: ["CT"]
        patterns:
            - regex: "(?i)\\btonnage\\s+report\\s+\\(fert\\)"
              confidence: 0.9
      - term: "Tonnage Report (Lime)" #CT
        states: ["CT"]
        patterns:
            - regex: "(?i)\\btonnage\\s+report\\s+\\(lime\\)"
              confidence: 0.9
      - term: "Monthly Fertilizer Tonnage Reports"
        states: ["AR"]
        patterns:
            - regex: "(?i)\\bmonthly\\s+fertilizer\\s+tonnage\\s+reports?\\b"
              confidence: 0.95

  amendment:
    canonical_name: "Registration Amendment"
    state_terms:
      - term: "Label Update Submission"
        states: []
        patterns:
            - regex: "(?i)\\blabel\\s+update\\s+submission\\b"
              confidence: 0.9
      - term: "Updated Labels" #Commonly used term
        states: []
        patterns:
           - regex: "(?i)\\bupdated\\s+labels?\\b"
             confidence: 0.95
      - term: "Label Revision"
        states: []
        patterns:
            - regex: "(?i)\\blabel\\s+revision\\b"
              confidence: 0.9
      - term: "Name Change"  # Specific change type
        states: []
        patterns:
            - regex: "(?i)\\bname\\s+change\\b"
              confidence: 0.9
      - term: "Guarantee Change" # Specific change type
        states: []
        patterns:
            - regex: "(?i)\\bguarantee\\s+change\\b"
              confidence: 0.9
      - term: "Registrant Change" # Specific change type
        states: []
        patterns:
            - regex: "(?i)\\bregistrant\\s+change\\b"
              confidence: 0.9

  exemption:
    canonical_name: "Exemption"
    state_terms:
      - term: "No Regulation" #When a product category is explicitly not regulated
        states: []
        patterns:
            - regex: "(?i)\\bno\\s+regulation\\b"
              confidence: 0.95
      - term: "Exempt"
        states: []
        patterns:
           - regex: "(?i)\\bexempt\\b"
             confidence: 0.9