# relationships.yaml
# Defines relationships between different parts of the ontology.

relationships:
  product_type_to_required_actions:
    # Fertilizer relationships
    "fertilizer.commercial":
      required: ["registration", "licensing", "tonnage"]  # Example: registration and tonnage are *always* required
      optional: ["amendment"] # Amendments might be needed
    "fertilizer.specialty":
      required: ["registration", "licensing", "tonnage"]
      optional: ["amendment"]
    "fertilizer.agricultural_mineral":
      required: ["registration", "tonnage"]  # Example: Assuming tonnage is always required
      optional: ["amendment", "licensing"]  # Licensing *might* be required, depending on state
    "fertilizer.bulk_agricultural_mineral": #added this
      required: ["registration", "tonnage"]  # Example: Assuming tonnage is always required
      optional: ["amendment", "licensing"]
    # Biostimulant relationships
    "biostimulant.biological_inoculant":
      required: ["registration"]
      optional: ["tonnage"]  # Some states might not require tonnage for inoculants
    "biostimulant.soil_amendment":
      required: ["registration"]
      optional: ["tonnage"]  # Some states might not require tonnage
    "biostimulant.plant_amendment":
      required: ["registration"]
      optional: ["tonnage"] # Some states might not require tonnage for inoculants
    "biostimulant.beneficial_substance":
      required: ["registration"] #some states may not require, add state specific overrides.
      optional: ["tonnage"]

    # Liming Material relationships
    "liming_material.agricultural_liming_material":
      required: ["registration", "licensing", "tonnage"] # Assuming tonnage is always required
      optional: ["amendment"]

     # Adjuvant relationships
    "adjuvant": # Adjuvants are a bit different, often regulated as pesticides
      required: ["registration"]  #  Often registered as a pesticide
      optional: ["licensing"]  # Licensing might be required depending on the state

  action_dependencies:
    # What actions depend on other actions?
    registration: []  # Registration is usually the first step, no dependencies
    licensing: []
    renewal: ["registration"]  # Renewal depends on a prior registration
    amendment: ["registration"]  # Amendment depends on an existing registration
    tonnage: ["registration", "licensing"]  # Tonnage reporting usually requires registration and licensing
    # You could add more fine-grained dependencies if needed

  # You could add other types of relationships here, for example:
  # product_category_to_required_documents:
  #   "fertilizer.commercial": ["label", "sds", "heavy_metals_analysis"]

  # state_to_required_actions: # (This could duplicate some of product_type_to_required_actions)
  #     CA:
  #         fertilizer.commercial: ["registration", "tonnage", "heavy_metals_testing"]