# status_workflows.yaml
# Defines the possible states and transitions for different regulatory actions.

status_workflows:
  registration: #Workflow for Product Registration
    initial_state: "submitted"  # The starting state
    states:
      - name: "submitted"
        next_states: ["under_review", "rejected", "approved", "needs_info"]
        description: "Application has been submitted and is awaiting review."
      - name: "under_review"
        next_states: ["approved", "rejected", "needs_info"]
        description: "Application is currently being reviewed by the regulatory agency."
      - name: "needs_info" # Added for clarity/more options
        next_states: ["under_review", "rejected", "withdrawn"] #can go back under review, be rejected, or be withdrawn
        description: "Additional information has been requested from the applicant."
      - name: "approved"
        next_states: ["renewal", "amendment", "inactive"] # Example next states
        description: "Application has been approved."
      - name: "rejected"
        next_states: []  # Terminal state
        description: "Application has been rejected."
      - name: "withdrawn" # Added to allow company to withdraw
        next_states: [] #Terminal State
        description: "Application has been withdrawn by the submitter"
      - name: "inactive" # Added to indicate a no-longer active, but previously approved
        next_states: ["renewal"]
        description: "Registration is no longer active (e.g., product discontinued)."

  licensing: # Example for a separate workflow
    initial_state: "submitted"
    states:
      - name: "submitted"
        next_states: ["review", "rejected", "approved", "needs_info"]
        description: "License application submitted, awaiting review."
      - name: "review"
        next_states: ["approved", "rejected", "needs_info"]
        description: "License application is under review."
      - name: "needs_info"
        next_states: ["review", "rejected", "withdrawn"]
        description: "Additional information requested."
      - name: "approved"
        next_states: ["renewal", "amendment", "inactive"]
        description: "License has been approved."
      - name: "rejected"
        next_states: []  # Terminal state
        description: "License application has been rejected"
      - name: "withdrawn" # Added to allow company to withdraw
        next_states: [] #Terminal State
        description: "Application has been withdrawn by the submitter"
      - name: "inactive" # Added to indicate a no-longer active, but previously approved
        next_states: ["renewal"]
        description: "Registration is no longer active (e.g., company out of business)."

  tonnage:  # Example of a simpler workflow.
    initial_state: "pending" # Tonnage report due
    states:
      - name: "pending"
        next_states: ["submitted", "overdue"]  #  Can either be submitted on time, or overdue
        description: "Tonnage report is due but has not yet been submitted."
      - name: "submitted"
        next_states: ["verified", "needs_correction"] # Next step is verification.
        description: "Tonnage report has been submitted."
      - name: "overdue"
        next_states: ["submitted", "reminder_sent"] #  If overdue, can still be submitted.
        description: "Tonnage report was not submitted by the deadline."
      - name: "reminder_sent"  # Added reminder step
        next_states: ["submitted", "delinquent"]
        description: "Reminder notification sent for overdue tonnage report."
      - name: "verified" # Final, good state
        next_states: []
        description: "Tonnage report has been verified and accepted."
      - name: "needs_correction"
        next_states: ["submitted"]
        description: "Tonnage report needs corrections"
      - name: "delinquent" # Final state, if no action taken after reminders
        next_states: []
        description: "Tonnage report is delinquent, and action may be required."

  renewal:
    initial_state: "pending_renewal"
    states:
      - name: "pending_renewal"
        next_states: ["submitted", "expired"]
        description: "Renewal is due soon"
      - name: "submitted"
        next_states: ["approved", "rejected", "needs_info"]
        description: "Renewal has been submitted"
      - name: "approved"
        next_states: []
        description: "Renewal Approved."
      - name: "rejected"
        next_states: []
        description: "Renewal Rejected."
      - name: "needs_info"
        next_states: ["submitted", "rejected"]
        description: "Additional info required for renewal."
      - name: "expired"
        next_states: []
        description: "Registration expired"
      - name: "withdrawn" # Added to allow company to withdraw
        next_states: [] #Terminal State
        description: "Application has been withdrawn by the submitter"

  amendment:
    initial_state: "submitted"
    states:
      - name: "submitted"
        next_states: ["approved", "rejected", "needs_info"]
        description: "Amendment has been submitted."
      - name: "approved"
        next_states: []
        description: "Amendment has been approved."
      - name: "rejected"
        next_states: []
        description: "Amendment has been rejected."
      - name: "needs_info"
        next_states: ["submitted", "rejected"]
        description: "Additional information requested for amendment."
      - name: "withdrawn" # Added to allow company to withdraw
        next_states: [] #Terminal State
        description: "Application has been withdrawn by the submitter"

  # Add more workflows as needed (e.g., for "label_submission," "exemption")