# product_categories.yaml
# Defines the hierarchical structure of product categories and subcategories.
# Maps state-specific terms to canonical names, including regex patterns for matching.

product_categories:
  fertilizer:
    canonical_name: "Fertilizer"
    priority: 1  # Higher number = higher priority (for conflict resolution)
    common_misspellings: ["fertlizer", "fertilser", "fert"] #For fuzzy matching
    related_terms: ["plant food", "plant nutrient", "NPK"] #For contextual clues
    exclusions: ["pesticide", "herbicide", "insecticide", "fungicide"] # Avoid misclassification
    subcategories:
      commercial:
        canonical_name: "Commercial Fertilizer"
        state_terms:
          - term: "Commercial Fertilizer"
            states: ["AL", "AR", "AZ", "CA", "CO", "CT", "DE", "DC", "FL", "GA", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MS", "MO", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WV", "WY"]
            patterns:
              - regex: "(?i)\\bcommercial\\s+fertilizer\\b"  # Case-insensitive, word boundaries
                confidence: 0.9
              - regex: "(?i)\\bcomm\\.?\\s+fertilizer\\b"  # Handles abbreviation "comm."
                confidence: 0.8
          - term: "Agricultural Fertilizer"
            states: ["CA"]
            patterns:
              - regex: "(?i)\\bagricultural\\s+fertilizer\\b"
                confidence: 0.9
              - regex: "(?i)\\bag\\s+fertilizer\\b"  # Common abbreviation
                confidence: 0.7
          - term: "Farm Fertilizer"
            states: ["KY"]
            patterns:
              - regex: "(?i)\\bfarm\\s+fertilizer\\b"
                confidence: 0.9
          - term: "Fertilizer" # A general term if a more specific doesn't fit
            states: ["AK","DC", "HI"]
            patterns:
              - regex: "(?i)\\bfertilizer\\b"
                confidence: 0.95 #High confidence because it's the base term.
      specialty:
        canonical_name: "Specialty Fertilizer"
        state_terms:
          - term: "Specialty Fertilizer"
            states: [ "AR", "AZ", "CA", "CO", "CT", "FL", "GA", "IA", "KS", "KY", "MA", "MD", "ME", "MI", "MN", "MS", "MO", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WV", "WY"]
            patterns:
              - regex: "(?i)\\bspecialty\\s+fertilizer\\b"
                confidence: 0.95
          - term: "Non-Agricultural Fertilizer"
            states: []
            patterns:
              - regex: "(?i)\\bnon-?agricultural\\s+fertilizer\\b" # Handles with and without hyphen
                confidence: 0.9
          - term: "Special Mix Fertilizer"
            states: []
            patterns:
              - regex: "(?i)\\bspecial\\s+mix\\s+fertilizer\\b"
                confidence: 0.8

      agricultural_mineral:
        canonical_name: "Agricultural Mineral"
        state_terms:
          - term: "Agricultural Mineral"
            states: ["CA"]
            patterns:
                - regex: "(?i)\\bagricultural\\s+mineral\\b"
                  confidence: 0.95

      bulk_agricultural_mineral:
        canonical_name: "Bulk Agricultural Mineral"
        state_terms:
          - term: "Bulk Agricultural Mineral"
            states: ["CA"]
            patterns:
                - regex: "(?i)\\bbulk\\s+agricultural\\s+mineral\\b"
                  confidence: 0.95

  biostimulant:
    canonical_name: "Biostimulant"
    priority: 2
    common_misspellings: []
    related_terms: ["plant growth regulator", "soil enhancer", "plant amendment"]
    exclusions: ["fertilizer", "pesticide", "herbicide"]
    subcategories:
      biological_inoculant:
        canonical_name: "Biological Inoculant"
        state_terms:
          - term: "Biological Inoculant"
            states: ["AL", "AR", "AZ", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WV", "WY"]
            patterns:
              - regex: "(?i)\\bbiological\\s+inoculant\\b"
                confidence: 0.9
          - term: "Pure or Mixed Cultures of Microorganisms"
            states: ["IN"]
            patterns:
              - regex: "(?i)\\bpure\\s+or\\s+mixed\\s+cultures\\s+of\\s+microorganisms?\\b"
                confidence: 0.9
          - term: "Legume Inoculant"
            states: ["OH"]
            patterns:
              - regex: "(?i)\\blegume\\s+inoculant\\b"
                confidence: 0.9
          - term: "Microbial Inoculant"
            states: ["HI", "NJ"]
            patterns:
                - regex: "(?i)\\microbial\\s+inoculant\\b"
                  confidence: 0.95
          - term: "Microbial Product" #HI uses this
            states: ["HI"]
            patterns:
                - regex: "(?i)\\bmicrobial\\s+product\\b"
                  confidence: 0.9
          - term: "Soil or Plant Inoculants"
            states: ["NY"]
            patterns:
                - regex: "(?i)\\bsoil\\s+or\\s+plant\\s+inoculants?\\b"
                  confidence: 0.9
          - term: "Seed Treatment Label" # Added based on CA
            states: ["CA"]
            patterns:
                - regex: "(?i)\\bseed\\s+treatment\\s+label\\b"
                  confidence: 0.9
      soil_amendment:
        canonical_name: "Soil Amendment"
        state_terms:
          - term: "Soil Amendment"
            states:  ["AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WV", "WY"]
            patterns:
              - regex: "(?i)\\bsoil\\s+amendment\\b"
                confidence: 0.95
          - term: "Soil Conditioner"
            states: ["DE", "MO"] #Added IA, DE
            patterns:
              - regex: "(?i)\\bsoil\\s+conditioner\\b"
                confidence: 0.9
          - term: "Auxiliary soil and plant substance" #From CA
            states: ["CA"]
            patterns:
                - regex: "(?i)\\bauxiliary\\s+soil\\s+and\\s+plant\\s+substance\\b"
                  confidence: 0.9
          - term: "Plant Amendment"
            states: ["CO", "ND"]
            patterns:
              - regex: "(?i)\\bplant\\s+amendment\\b"
                confidence: 0.9
      plant_amendment: # Added based on CO, ND
        canonical_name: "Plant Amendment"
        state_terms:
          - term: "Plant Amendment"
            states: ["CO", "ND"]
            patterns:
              - regex: "(?i)\\bplant\\s+amendment\\b" #same pattern, higher confidence in this context.
                confidence: 0.95
      beneficial_substance:  # Added, covers multiple subcategories.
        canonical_name: "Beneficial Substance"
        state_terms:
          - term: "Beneficial Substance"
            states: ["AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WV", "WY"]
            patterns:
              - regex: "(?i)\\bbeneficial\\s+substance\\b"
                confidence: 0.9

  liming_material:
    canonical_name: "Liming Material"
    priority: 3
    common_misspellings: ["limeing"]
    related_terms: ["agricultural lime", "ag lime", "lime"]
    exclusions: []
    subcategories:
      agricultural_liming_material:
        canonical_name: "Agricultural Liming Material"
        state_terms:
          - term: "Agricultural Liming Material"
            states: ["NH", "NY"]
            patterns:
                - regex: "(?i)\\bagricultural\\s+liming\\s+material\\b" #From before
                  confidence: 0.9
                - regex: "(?i)\\bagricultural\\s+lime\\b" #From before
                  confidence: 0.8
          - term: "Lime Material"
            states: ["AL", "CO", "CT", "DE", "FL", "GA", "IA", "KY", "MD", "ME", "MS", "NJ", "OK", "TN"]
            patterns:
                - regex: "(?i)\\blime\\s+material\\b"
                  confidence: 0.9
          - term: "Liming Material"
            states:  ["AR", "AZ", "CT", "DE", "FL", "GA", "IA", "KS", "KY", "LA", "ME", "MN", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WV", "WY"]
            patterns:
              - regex: "(?i)\\bliming\\s+material\\b"
                confidence: 0.95

  adjuvant:
      canonical_name: "Adjuvant"
      priority: 4
      common_misspellings: []
      related_terms: ["surfactant", "wetting agent"]
      exclusions: []
      subcategories: {}
      state_terms:
        - term: "Adjuvant"
          states: ["AR", "AZ", "CA", "CO", "DE", "ID"]
          patterns:
            - regex: "(?i)\\badjuvant\\b"
              confidence: 0.95
        - term: "Pesticide" #Some states classify adjuvants as pesticides
          states: ["AL", "AR", "CA", "DE", "ID", "KY", "TN"]
          patterns:
            - regex: "(?i)\\bpesticide\\b"
              confidence: 0.7  #Lower confidence, as it could be other pesticides
        - term: "Adjuvant/Pesticide" #Combined term
          states: ["AR", "CA", "DE"]
          patterns:
            - regex: "(?i)\\badjuvant\\s*/\\s*pesticide\\b" #Handles the "/"
              confidence: 0.9