product_categories:
  fertilizer:
    canonical_name: "Fertilizer"
    description: "Products containing one or more recognized plant nutrients used for promoting plant growth."
    regex: "\\b(?i)(fertilizer|fert|plant food|plant nutrient)\\b"
    subcategories:
      commercial:
        canonical_name: "Commercial Fertilizer"
        description: "Fertilizers generally for agricultural use, often in bulk or larger quantities."
        regex: "\\b(?i)(commercial fertilizer|agricultural? fertilizer|farm fertilizer|fertilizer(?!\\s*(dealer|manufacturer|manufacturers|mixing|blender|license|permit|products|inspection|tonnage)))\\b"
        # The negative lookahead prevents matching phrases like "fertilizer dealer permit"
        # Added "agricultural" and "farm"
        state_terms:
          - term: "Commercial Fertilizer"
            states: ["AL", "AR", "AZ", "CO", "CT", "DE", "FL", "GA", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MS", "MO", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WV", "WY"]
          - term: "Agricultural Mineral"
            states: ["CA"]
          - term: "Bulk Agricultural Mineral"
            states: ["CA"]
          - term: "Farm Fertilizer"
            states: ["KY"]
          - term: "Fertilizer" # DC, HI  General term
            states: ["DC", "HI", "AK"] # Added AK. AK has no regulation, but still should be tagged as fertilizer for context

      specialty:
        canonical_name: "Specialty Fertilizer"
        description: "Fertilizers typically for non-commercial use, such as home gardens, lawns, and houseplants."
        regex: "\\b(?i)(specialty fertilizer|non-ag fertilizer|non-agricultural fertilizer|home (and|&) garden|small package)\\b" #Added more terms
        state_terms:
          - term: "Specialty Fertilizer"
            states: ["AR", "AZ", "CA", "CO", "CT", "FL", "GA", "IA", "KS", "KY", "MA", "MD", "ME", "MI", "MN", "MS", "MO", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WV", "WY"]
          - term: "Non-Agricultural Fertilizer"
            states: [] #GA uses this term
          - term: "Commercial Fertilizer - ≤ 10lbs" #DE
            states: ["DE"]
          - term: "Commercial Fertilizer - >10lbs" #DE
            states: ["DE"]
          - term: "Commercial Fertilizer - BOTH SIZES"  #DE
            states: ["DE"]
          - term: "Specialty Fertilizer >10 lbs" #GA
            states: ["GA"]
          - term: "Specialty Fertilizer ≤10 lbs" #GA
            states: ["GA"]
          - term: "Specialty Fertilizer 49# or less" #FL
            states: ["FL"]
          - term: "Specialty Fertilizer Greater than 49#" #FL, uses license
            states: ["FL"]
          - term: "Specialty Fertilizer >10 lbs" #GA
            states: ["GA"]
          - term: "Specialty Fertilizer ≤10 lbs" #GA
            states: ["GA"]
      agricultural_mineral:
        canonical_name: "Agricultural Mineral"
        description:  "Inorganic fertilizer, often with lower NPK values."
        regex: "\\b(?i)(agricultural mineral)\\b"
        state_terms:
            - term: "Agricultural Mineral"
              states: ["CA"]

      bulk_agricultural_mineral:
        canonical_name: "Bulk Agricultural Mineral"
        description: "Agricultural minerals in bulk quantities."
        regex: "\\b(?i)(bulk agricultural mineral)\\b"
        state_terms:
          - term: "Bulk Agricultural Mineral"
            states: ["CA"]

  biostimulant:
    canonical_name: "Biostimulant"
    description: "Substances or microorganisms that enhance plant growth, nutrient uptake, or stress tolerance, but are not primarily fertilizers."
    regex: "\\b(?i)(biostimulant|plant growth regulator|plant amendment|soil amendment|soil conditioner|plant inoculant|auxiliary soil and plant substance|beneficial substance)\\b" # Broad regex, includes related terms.
    subcategories:
      biological_inoculant:
        canonical_name: "Biological Inoculant"
        description: "Products containing beneficial microorganisms."
        regex: "\\b(?i)(biological inoculant|microbial inoculant|inoculant|microbial product|pure or mixed cultures of microorganisms)\\b"
        state_terms:
          - term: "Biological Inoculant"
            states: ["AL", "AZ", "CO", "CT", "DE", "FL", "GA", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WV", "WY"] #All States
          - term: "Pure or Mixed Cultures of Microorganisms"
            states: ["IN"]
          - term: "Microbial Product"
            states: ["HI"]
          - term: "Seed Treatment Label" # CA
            states: ["CA"]
          - term: "Microbial Inoculant"  #NJ
            states: ["NJ", "HI"]

      soil_amendment:  # Grouped related terms under one subcategory
        canonical_name: "Soil Amendment"
        description: "Materials added to soil to improve its physical or chemical properties."
        regex: "\\b(?i)(soil amendment|soil conditioner|plant amendment|auxiliary soil and plant substance|soil and plant amendment)\\b"  # Added "soil and plant amendment"
        state_terms:
          - term: "Soil Amendment"
            states:  ["AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WV", "WY"]
          - term: "Soil Conditioner"
            states: ["DE", "MO"] #Added IA, DE
          - term: "Soil Conditioner - \\u2264 10lbs" #DE
            states: ["DE"]
          - term: "Soil Conditioner - > 10lbs"
            states: ["DE"]
          - term: "Soil Conditioner - BOTH SIZES" #DE
            states: ["DE"]
          - term: "Auxiliary soil and plant substance" #CA
            states: ["CA"]
          - term: "Plant Amendment" #Added based on CO and ND data
            states: ["CO", "ND"]
          - term: "Plant & Soil Amendments" #CO
            states: ["CO"]
          - term: "Soil and Plant Amendment" #MS
            states: ["MS"]

      plant_amendment: #CO and ND specific
        canonical_name: "Plant Amendment"
        description: "Materials added to plants directly"
        regex: "\\b(plant amendment)\\b"
        state_terms:
          - term: "Plant Amendment"
            states: ["CO", "ND"]

      beneficial_substance:
        canonical_name: "Beneficial Substance"
        description: "Substances that promote plant growth"
        regex: "\\b(beneficial substance)\\b"
        state_terms:
            - term: "Beneficial Substance"
              states:  ["AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WV", "WY"]

  liming_material:
    canonical_name: "Liming Material"
    description: "Products used to raise soil pH (reduce acidity)."
    regex: "\\b(?i)(liming material|ag lime|agricultural lime|lime)\\b"
    subcategories:
      agricultural_liming_material:
        canonical_name: "Agricultural Liming Material"
        description: "Liming materials specifically for agricultural use."
        regex: "\\b(?i)(agricultural liming material|ag lime|lime product)\\b"  #Added "lime product"
        state_terms:
          - term: "Agricultural Liming Material"
            states: ["NH", "NY"]
          - term: "Lime Material"
            states: ["AL", "CO", "CT", "DE", "FL", "GA", "IA", "KY", "MD", "ME", "MS", "NJ", "OK", "TN", "UT", "VA", "VT", "WA", "WV", "WY"]
          - term: "Liming Material"
            states:  ["AR", "AZ", "CT", "DE", "FL", "GA", "IA", "KS", "KY", "LA", "ME", "MN", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WV", "WY"]
          - term: "Ag Lime" #Added based on MO, TN
            states: ["MO", "TN"]
      lime_product:   #MO, TN, added
        canonical_name: "Lime Product"
        description: "Lime Products for Ag Use."
        regex: "\\b(?i)(lime product)\\b"
        state_terms:
          - term: "Lime Product"
            states: ["MO", "TN"]

  adjuvant:
    canonical_name: "Adjuvant"
    description: "Substances added to a pesticide mixture to improve its effectiveness."
    regex: "\\b(?i)(adjuvant|surfactant|wetting agent)\\b" # Added more terms
    subcategories: {}
    state_terms:
        - term: "Adjuvant"
          states: ["AR", "AZ", "CO", "DE", "ID","KY","TN"]
        - term: "Pesticide"
          states: ["AL", "AR", "CA","DE","ID","KY", "TN"]
        - term: "Adjuvant/Pesticide"
          states: ["AR", "CA", "DE"]

  organic_input_material:  # OIM, added based on WA OIM data.
    canonical_name: "Organic Input Material"
    description: "Materials approved for use in organic crop production."
    regex: "\\b(?i)(organic input material|OIM|OMRI listed|organic material)\\b" # Added OMRI.
    subcategories: {}
    state_terms:
        - term: "Organic Input Material"
          states: ["WA", "CA"] #Added CA
        - term: "Organic Materials Input"
          states: ["CA"]

  no_regulation: # Explicitly not regulated.  Important for completeness.
    canonical_name: "No Regulation"
    description: "Product category is explicitly not regulated in this state."
    regex: "\\b(?i)(no regulation|exempt from regulation)\\b"
    state_terms:
      - term: "No Regulation"
        states: ["AK", "AR","AZ", "CA", "CO", "CT", "DC", "HI", "IN", "NC", "NY", "SD"]