# Configuration Version Control
# Defines versioning rules and tracks current versions of all configuration files

version_control:
  schema_version: "1.0.0"  # Overall schema version
  min_compatible_version: "1.0.0"
  
  # Versioning rules
  version_format: "MAJOR.MINOR.PATCH"
  rules:
    major: "Breaking changes that require code updates"
    minor: "Backwards-compatible additions (new fields, patterns)"
    patch: "Content updates (new terms, companies, patterns)"
    
  # Current versions of configuration files
  current_versions:
    regulatory_actions: "1.0.0"
    product_categories: "1.0.0"
    document_types: "1.0.0"
    company_codes: "1.0.0"
    state_patterns: "1.0.0"
    
  # Version history tracking
  history:
    regulatory_actions:
      - version: "1.0.0"
        date: "2024-03-14"
        changes:
          - "Initial version with base types, status types, and workflow status"
          - "Detailed state-specific terms for registration, licensing, tonnage"
    
    product_categories:
      - version: "1.0.0"
        date: "2024-03-14"
        changes:
          - "Initial version with hierarchical product categories"
          - "State-specific terms and patterns for all major categories"
    
    document_types:
      - version: "1.0.0"
        date: "2024-03-14"
        changes:
          - "Initial version with base document types"
          - "Validation rules and required fields"
    
    company_codes:
      - version: "1.0.0"
        date: "2024-03-14"
        changes:
          - "Initial version with company code mappings"
          - "Validation rules for 3-letter codes"
    
    state_patterns:
      - version: "1.0.0"
        date: "2024-03-14"
        changes:
          - "Initial version with state recognition patterns"
          - "Full state name mappings and abbreviations"

  # Migration requirements
  migrations_required:
    "1.0.0": []  # No migrations needed for initial version
    
  # Validation schema versions
  validation_schemas:
    "1.0.0": "schemas/v1_0_0/"  # Path to JSON schema files for v1.0.0 