name: Branch Name Check

on:
  pull_request:
    branches: [ main, master, develop, staging ]

jobs:
  branch-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Branch Name
        run: |
          BRANCH_NAME=${GITHUB_HEAD_REF}
          if [[ ! $BRANCH_NAME =~ ^(feature|bugfix|test|docs|refactor)/GH-[0-9]+-[a-z0-9-]+$ ]]; then
            echo "❌ Branch name must match pattern: type/GH-number-description"
            exit 1
          fi 